// Package domain provides domain functionality for the IMB platform.
package domain

import (
	"time"

	"github.com/google/uuid"
)

// Base holds the common identity and timestamp fields shared by all domain
// entities. It uses a UUID primary key generated by PostgreSQL and plain
// time.Time timestamps managed automatically by GORM conventions.
//
// No GORM package import is required here; the gorm struct tags are plain
// string annotations interpreted at runtime by the ORM layer.
type Base struct {
	ID        uuid.UUID `gorm:"type:uuid;primaryKey;default:gen_random_uuid()"`
	CreatedAt time.Time
	UpdatedAt time.Time
}
